# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-22 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='项目名称')),
                ('version', models.CharField(max_length=40, verbose_name='项目版本')),
                ('info', models.CharField(max_length=100, verbose_name='版本描述')),
                ('detail', models.TextField(verbose_name='更新详情')),
                ('status', models.IntegerField(choices=[(0, '申请'), (1, '已审核'), (2, '灰度'), (3, '上线'), (4, '取消上线')], default=0, verbose_name='上线状态')),
                ('console_output', models.TextField(default='', help_text='jenkins控制台输出的结果', verbose_name='上线输出结果')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('deploy_time', models.DateTimeField(auto_now=True, verbose_name='上线完成时间')),
            ],
        ),
    ]
