# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 11:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='项目名称')),
                ('version', models.CharField(max_length=40, verbose_name='项目版本')),
                ('info', models.CharField(max_length=100, verbose_name='版本描述')),
                ('etail', models.TextField(verbose_name='更新详情')),
                ('status', models.IntegerField(choices=[(0, '申请'), (1, '灰度'), (2, '上线'), (3, '取消上线')], default=0, verbose_name='上线状态')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('deploy_time', models.DateTimeField(auto_now=True, verbose_name='上线完成时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to=settings.AUTH_USER_MODEL, verbose_name='指派人')),
            ],
        ),
    ]
