# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-07 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deploy',
            old_name='etail',
            new_name='detail',
        ),
    ]
