# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-07 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0002_auto_20180907_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deploy',
            old_name='assigned_to',
            new_name='assign_to',
        ),
    ]
