# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-07 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('release', '0003_auto_20180907_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='console_output',
            field=models.TextField(default='', help_text='jenkins控制台输出的结果', verbose_name='上线输出结果'),
        ),
        migrations.AddField(
            model_name='deploy',
            name='reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deploy',
            name='assign_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to=settings.AUTH_USER_MODEL, verbose_name='上线人'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='status',
            field=models.IntegerField(choices=[(0, '申请'), (1, '已审核'), (2, '灰度'), (3, '上线'), (4, '取消上线')], default=0, verbose_name='上线状态'),
        ),
    ]
