# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-08 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0004_auto_20180907_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to=settings.AUTH_USER_MODEL, verbose_name='上线人'),
        ),
    ]
