---                                                                                         
- hosts: all 
  become_user: root
  gather_facts: no
  tasks:
  - name: touch cc.txt
    file: path=/tmp/cc.txt state=touch  mode=0777